#!/bin/bash

alias go='gnome-open'
alias wget="wget --no-check-certificate"
alias watchmedo="fab -H wall-e copy; watchmedo shell-command --recursive --patterns='*.py;*.js;*.css;*.html;*.scss' --command='fab -H wall-e copy'"

