#!/bin/bash

[ -d "/usr/lib/jvm/java-6-sun" ] && export JAVA_HOME=/usr/lib/jvm/java-6-sun
[ -d "/opt/java/64/jdk1.6.0_32" ] && export JAVA_HOME=/opt/java/64/jdk1.6.0_32
[ -d "/usr/lib/jvm/jdk1.6.0_37" ] && export JAVA_HOME=/usr/lib/jvm/jdk1.6.0_37

