#!/bin/bash

[[ -d /var/lib/gems/1.8/bin ]] && export PATH=$PATH:/var/lib/gems/1.8/bin

[[ -d "$HOME/.rvm/bin" ]] && export PATH=$PATH:$HOME/.rvm/bin

[[ -d "$HOME/.rvm/gems/ruby-1.9.3-p327/bin" ]] && export PATH=$PATH:"$HOME/.rvm/gems/ruby-1.9.3-p327/bin"

# Load RVM into a shell session *as a faction*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

