#!/bin/bash

if [ -d /opt/SenchaSDKTools-2.0.0-beta3 ]; then
    export SENCHA_SDK_TOOLS_2_0_0_BETA3=/opt/SenchaSDKTools-2.0.0-beta3
    export PATH=$PATH:/opt/SenchaSDKTools-2.0.0-beta3:/opt/SenchaSDKTools-2.0.0-beta3/bin
fi
